djangofirstexample/djangofirstexample/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views as v
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls,name="admin"),
    path('saifu',v.index,name="saifu"),
    path('about',v.about,name="about"),
    path('service',v.service,name="service"),
    path('add',v.add,name="add"),
    path('savedata',v.savedata,name="savedata"),
    path('show',v.show,name="show"),
    path('edit/<int:id>',v.edit,name="edit"),
    path('update/<int:id>',v.update,name="update"),
    path('delete/<int:id>',v.delete,name="delete"),
]

urlpatterns += staticfiles_urlpatterns()

djangofirstexample/myapp/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
	eid = models.CharField(max_length = 20)
	ename = models.CharField(max_length = 100)
	eemail = models.EmailField()
	econtact = models.CharField(max_length = 20)
	class Meta:
		db_table = 'employee'

djangofirstexample/myapp/forms.py
from django import forms
from myapp.models import Employee

class EmployeeForm(forms.ModelForm):
	class Meta:
		model = Employee
		fields = "__all__"

djangofirstexample/myapp/views.py
from django.shortcuts import render,render_to_response,redirect
from myapp.forms import EmployeeForm
from myapp.models import Employee
# Create your views here.

def index(request):
	return render_to_response('index.html')

def about(request):
	return render_to_response('about.html')

def service(request):
	return render_to_response('service.html')

def add(request):
	return render(request, "add.html")

def savedata(request):
	request.POST
	employee = Employee(eid=request.POST['eid'],ename=request.POST['ename'],eemail=request.POST['eemail'],econtact=request.POST['econtact'])
	employee.save()
	return  redirect('/show')
def show(request):
	employees = Employee.objects.all()
	return render(request, "crudshow.html", {'employees':employees })

def edit(request, id):
	employee = Employee.objects.get(id = id)
	return render(request,"edit.html",{'employee':employee})

def update(request,id):
	employee = Employee.objects.get(id = id)
	employee.eid = request.POST['eid']
	employee.ename = request.POST['ename']
	employee.eemail = request.POST['eemail']
	employee.econtact = request.POST['econtact']
	employee.save()
	return redirect('/show')
	

def delete(request,id):
	employee = Employee.objects.get(id = id)
	employee.delete()
	return redirect("/show")

djangofirstexample/myapp/templates/about.html
{% extends 'base_layout.html' %}

{% block content%}
    <!-- Jumbotron Header -->
    <header class="jumbotron my-4">
      <h1 class="display-3">About Welcome!</h1>
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>
      <a href="#" class="btn btn-primary btn-lg">Call to action!</a>
    </header>

    <!-- Page Features -->
    
    <!-- /.row -->

{% endblock %}

  

djangofirstexample/myapp/templates/add.html
{% extends 'base_layout.html'%}

{% block content%}
  <a class="btn btn-secondary" href="{% url 'show'%}">Services</a>

<form method="POST" class="post-form" action="/savedata">
    {% csrf_token %}

<div class="form-group">
    <label for="exampleFormControlInput1">employee id </label>
    <input type="text" name="eid" id="id_eid"> </div>

 <div class="form-group">
    <label for="exampleFormControlInput1">Employee Name  </label>
    <input type="text" name="ename" id="id_ename">
 </div>

 <div class="form-group">
    <label for="exampleFormControlInput1">Employee email  </label>
     <input type="text" name="eemail" id="id_eemail">
 </div>

 <div class="form-group">
    <label for="exampleFormControlInput1">Employee contact  </label>
     <input type="text" name="econtact" id="id_econtact">
 </div>

 <div class="form-group">
    <button type="submit" class="btn-primary btn-sm">save</button>
 </div>
 </form>

{% endblock%}

djangofirstexample/myapp/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Heroic Features - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/heroic-features.css'%}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about'%}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'service'%}">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'add'%}">Crud System</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

</body>

</html>

djangofirstexample/myapp/templates/crudshow.html
{% extends 'base_layout.html'%}

{% block content%}
	<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Employee Id</th>
      <th scope="col">Employee name</th>
      <th scope="col">Employee email</th>
      <th scope="col">Employee contact</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    
    {% for employee in employees %}
    {% with "1" as name %}   
    <tr>
      <td>{{ name }}</td>
      <th>{{employee.eid}}</th>
      <td>{{employee.ename}}</td>
      <td>{{employee.eemail}}</td>
      <td>{{employee.econtact}}</td>
      <td>
        <a href="/edit/{{employee.id }}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
         <a href="/delete/{{employee.id }}"><span class="glyphicon glyphicon-pencil">delete</span></a>
      </td>
    </tr>
   {% endwith %}

    {% endfor %}

   
  </tbody>
</table>

{% endblock%}

djangofirstexample/myapp/templates/edit.html
{% extends 'base_layout.html'%}

{% block content%}
	<a class="btn btn-secondary" href="{% url 'show'%}">Services</a>

<form method="POST" class="post-form" action="/update/{{employee.id}}">
	{% csrf_token %}

<div class="form-group">
    <label for="exampleFormControlInput1">employee id </label>
    <input type="text" name="eid" id="id_eid" value="{{employee.eid}}">
 </div>

 <div class="form-group">
    <label for="exampleFormControlInput1">Employee Name  </label>
    <input type="text" name="ename" id="id_ename" value="{{employee.ename}}">
 </div>

 <div class="form-group">
    <label for="exampleFormControlInput1">Employee email  </label>
     <input type="text" name="eemail" id="id_eemail" value="{{employee.eemail}}">
 </div>

 <div class="form-group">
    <label for="exampleFormControlInput1">Employee contact  </label>
     <input type="text" name="econtact" id="id_econtact" value="{{employee.econtact}}">
 </div>

 <div class="form-group">
    <button type="submit" class="btn-primary btn-sm">save</button>
 </div>
 </form>

{% endblock%}

djangofirstexample/myapp/templates/index.html
{% extends 'base_layout.html' %}

{% block content%}
    <!-- Jumbotron Header -->
    <header class="jumbotron my-4">
      <h1 class="display-3">A Warm Welcome!</h1>
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>
      <a href="#" class="btn btn-primary btn-lg">Call to action!</a>
    </header>

    <!-- Page Features -->
    <div class="row text-center">

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="http://placehold.it/500x325" alt="">
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Find Out More!</a>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="http://placehold.it/500x325" alt="">
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni sapiente, tempore debitis beatae culpa natus architecto.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Find Out More!</a>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="http://placehold.it/500x325" alt="">
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Find Out More!</a>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="http://placehold.it/500x325" alt="">
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni sapiente, tempore debitis beatae culpa natus architecto.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Find Out More!</a>
          </div>
        </div>
      </div>

    </div>
    <!-- /.row -->

{% endblock %}

  

djangofirstexample/myapp/templates/service.html
{% extends 'base_layout.html'%}

{% block content%}

<header class="jumbotron my-4">
      <h1 class="display-3">Services page!</h1>
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>
      <a href="#" class="btn btn-primary btn-lg">Call to action!</a>
    </header>

{% endblock%}